language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
sudo: required

cache:
  directories:
    - $HOME/.m2

addons:
  srcclr: true

deploy:
  provider: script
  script: mvn deploy -Dmaven.test.skip -s settings.xml
  skip_cleanup: true
  on:
    branch: develop
    jdk: oraclejdk8
    condition: $TRAVIS_PULL_REQUEST = "false"
